create table if not exists public.study_canonical_cache (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  storage_path text not null,
  canonical_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint study_canonical_cache_unique unique (user_id, storage_path)
);

create index if not exists idx_study_canonical_cache_user_storage
  on public.study_canonical_cache (user_id, storage_path);

alter table public.study_canonical_cache enable row level security;

-- Service-role edge functions can write/read regardless of RLS.
-- Keep strict user policies for dashboard or client-side reads if needed.
drop policy if exists "Users can read own canonical cache" on public.study_canonical_cache;
create policy "Users can read own canonical cache"
  on public.study_canonical_cache
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can upsert own canonical cache" on public.study_canonical_cache;
create policy "Users can upsert own canonical cache"
  on public.study_canonical_cache
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.set_study_canonical_cache_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_study_canonical_cache_updated_at on public.study_canonical_cache;
create trigger trg_study_canonical_cache_updated_at
before update on public.study_canonical_cache
for each row
execute function public.set_study_canonical_cache_updated_at();
